replicaCount: 1

app:
  rootPath: "/GitOps-Starter"

image:
  repository: fastapi-gitops-starter
  tag: latest
  pullPolicy: Never

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: minikube.test
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
